version: "3.1"
services:
  db:
    image: mysql
    container_name: mysql-wordpress
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpress_local
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./wordpress-db/dump:/docker-entrypoint-initdb.d
      - ./wordpress-db/conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
      - "./wordpress/:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress_local
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: test


volumes:
  persistent:
