version: '3.1'
services:
#solo servicio wordpress
  db:
    image: mysql
    container_name: mysql-wordpress
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: wordpress_local
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - persistent:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      #- ./wordpress_local:/docker-entrypoint-initdb.d
    entrypoint:
      - docker-entrypoint.sh
      - mysqld
      - --init-file
      - /docker-entrypoint-initdb.d/


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8080:80
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test

  wordpress:
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes:
      - ./content/themes:/var/www/html/wp-content/themes
      - ./content/plugins:/var/www/html/wp-content/plugins
      - ./content/uploads:/var/www/html/wp-content/uploads
      - ./config:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: test
#solo servicio wordpress

volumes:
  persistent:

